name: medchain_emergency
description: Emergency hospital coordination system using blockchain and AI

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Animation
  flutter_animate: ^4.5.2
  glassmorphism: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  lottie: ^2.7.0
  shimmer: ^3.0.0
  
  # Maps & Location
  geolocator: ^12.0.0
  geocoding: ^2.1.1
  
  # HTTP & Connectivity
  http: ^1.1.0
  dio: ^5.8.0+1
  connectivity_plus: ^5.0.2
  
  # State Management
  provider: ^6.1.5
  get: ^4.6.6
  
  # Storage & Preferences
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Blockchain & Web3
  web3dart: ^2.7.3
  walletconnect_flutter_v2: ^2.1.12
  
  # Utils
  intl: ^0.18.1
  logger: ^2.0.2
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/contract-address/
    - assets/contracts/
  #
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700